AllCops:
  TargetRubyVersion: 2.1

Style/Lambda:
  EnforcedStyle: literal

Style/MutableConstant:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

# Some methods with 'set_' prefix are part of the public API
# e.g. 'set_user_id'
Naming/AccessorMethodName:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  AllowedNames: n, id, ip

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 25

Metrics/ParameterLists:
  Enabled: false

Metrics/LineLength:
  Max: 120
  IgnoredPatterns: ["^ *#"]

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
